eversion: "3"

services:
  dj-mariadb:
    image: mariadb
    environment:
      - CONTAINER_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
      - MYSQL_USER=domjudge
      - MYSQL_DATABASE=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_ROOT_PASSWORD=rootpw
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - ./data/db:/var/lib/mysql

  domjudge:
    image: domjudge/domserver
    environment:
      - CONTAINER_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_ROOT_PASSWORD=rootpw
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    links:
      - dj-mariadb:mariadb
    ports:
      - 12345:80
    privileged: true
